### ISSUE TITLE
Is it possible to retrieve risco sensor states?

### ISSUE THREAD

**Issue by speedyyellow** [szlaskidaniel/homebridge-risco-alarm#2]
We have a bunch of PIR's around the house for the alarm along with some door contact switches, it would be awesome if it was possible to expose these sensors to Homebridge via this plugin.  Do you know if the webapp has access to that level of information? or even if these sensors are active when the alarm is not armed?

**Comment by szlaskidaniel** [comment]
Hi, in theory this should be possible, as when we call GET https://www.riscocloud.com/ELAS/WebUI/Security/GetCPState , we receive status for all defined detectors.


`
{
"id":0,
"bypassed":false,
"filter":"",
"classAttrib":"",
"data_icon":"detector",
"name":"Wejście",
"strTimeval":"15/03/2018 19:23"
},
{
"id":1,
"bypassed":false,
"filter":"",
"classAttrib":"",
"data_icon":"detector",
"name":"Garaż",
"strTimeval":"15/03/2018 19:24"
},
`

Unfortunately there are 2 issues. First, of all, we do not always receive those data (I believe that only during the change), second thing, I'm not familiar enough with Homebridge Plugins to create this kind of dev. 
Because what you're looking for is a single plugin that creates a bunch of "detectors" with ON/OFF states (like motion sensors) - this should be dynamic, to match different installations.
Definitely possible, but we need help from more skilled guy from Homebridge Plugin itself (I can help with risco API requests)

**Comment by tkboyle** [comment]
Keep up the good work szlaskidaniel. I had been attempting to arm/disarm using post commands and gave up as I wasn't getting anywhere fast. The goal was to ultimately to use homebridge. Massive respect to you my friends for sharing this information. It's a pretty niche product so I'm stoked.

**Comment by speedyyellow** [comment]
Thanks for getting back to me. That info looks like the sensor data you can view in the mobile app. Sadly it only shows that the sensor is enabled and not what the sensor reading is.
